services:
  uptime-kuma:
    image: louislam/uptime-kuma:latest
    container_name: uptime-kuma
    restart: unless-stopped
    ports:
      - "9003:9003"
    networks:
      - cloudflare_tunnel_net
    volumes:
      - uptime_kuma_data:/app/data
    environment:
      - TZ=UTC-3
      - UMASK=0022
      - PORT=9003 # Porta padrão 3001 remapeada internamente no container para 9003
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:9003"]
      interval: 30s
      retries: 3
      start_period: 10s
      timeout: 5s
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"

  forgejo:
    image: codeberg.org/forgejo/forgejo:12
    container_name: forgejo
    environment:
      - USER_UID=1000
      - USER_GID=1000
    restart: unless-stopped
    volumes:
      - forgejo_data:/data
      - /etc/timezone:/etc/timezone:ro
      - /etc/localtime:/etc/localtime:ro
    ports:
      - "9002:3000"
      - "222:22"
    networks:
      - cloudflare_tunnel_net

  vaultwarden:
    image: vaultwarden/server:latest
    container_name: vaultwarden
    restart: unless-stopped
    environment:
      DOMAIN: ${VW_DOMAIN}
    ports:
      - "9001:80"
    volumes:
      - vaultwarden_data:/data/
    networks:
      - cloudflare_tunnel_net

  portainer:
    image: portainer/portainer-ce:2.33.0
    container_name: portainer
    restart: unless-stopped
    ports:
      - "9000:9000"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - portainer_data:/data
    networks:
      - cloudflare_tunnel_net

  rclone-sync:
    image: rclone/rclone:latest
    container_name: rclone-sync
    restart: unless-stopped
    volumes:
      - ./rclone_config:/config/rclone
      # Monta os volumes dos outros serviços como APENAS LEITURA :ro
      - uptime_kuma_data:/data/uptime_kuma:ro
      - forgejo_data:/data/forgejo:ro
      - vaultwarden_data:/data/vaultwarden:ro
      - portainer_data:/data/portainer:ro
    entrypoint: /bin/sh
    command: -c "while true; do rclone sync /data/ ${RCLONE_NAME}:Backups -v --log-file /dev/stdout; echo 'Backup finalizado. Aguardando ${BACKUP_SLEEP} segundos para o próximo'; sleep ${BACKUP_SLEEP}; done"

  cloudflare-tunnel:
    image: cloudflare/cloudflared:latest
    container_name: cloudflare-tunnel
    restart: unless-stopped
    command: tunnel run --token ${CLOUDFLARE_TOKEN}
    volumes:
      - ~/.cloudflared:/etc/cloudflared
    networks:
      - cloudflare_tunnel_net

networks:
  cloudflare_tunnel_net:
    name: cloudflare_tunnel_net
    driver: bridge

volumes:
  portainer_data:
    name: portainer_data
  vaultwarden_data:
    name: vaultwarden_data
  forgejo_data:
    name: forgejo_data
  uptime_kuma_data:
    name: uptime_kuma_data
